services:
  gnosari-engine:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples
      - ./db:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import gnosari; print('Gnosari engine is ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # MinIO S3 API port
      - "9001:9001" # MinIO Console port
    volumes:
      - ./protected/minio_data:/data # Mount a named volume for persistent data storage
    environment:
      MINIO_ROOT_USER: user # Replace with your desired username
      MINIO_ROOT_PASSWORD: password123 # Replace with your desired strong password
    command: server --console-address ":9001" /data
