services:
  gnosari-engine:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples
      - ./db:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import gnosari; print('Gnosari engine is ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # MinIO S3 API port
      - "9001:9001" # MinIO Console port
    volumes:
      - ./protected/minio_data:/data # Mount a named volume for persistent data storage
    environment:
      MINIO_ROOT_USER: user # Replace with your desired username
      MINIO_ROOT_PASSWORD: password123 # Replace with your desired strong password
    command: server --console-address ":9001" /data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./protected/redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A gnosari.queue.app.celery_app flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=admin:admin
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./src:/app/src
