name: "Custom Embedchain Configuration Example"
description: "A team demonstrating custom Embedchain configuration options"

# Define knowledge bases with custom Embedchain configuration
knowledge:
  - name: custom_website_docs
    type: website
    description: "Website documentation with custom chunking and embedding configuration"
    config:
      # Embedchain configuration using App.from_config structure
      llm:
        provider: "openai"
        config:
          model: "gpt-4o"
          temperature: 0.1
          max_tokens: 1000
      embedder:
        provider: "openai"
        config:
          model: "text-embedding-3-small"
      chunker:
        chunk_size: 1000
        chunk_overlap: 200
        length_function: "len"
    data:
      - "https://example.com/docs"
      - "https://example.com/api"

  - name: custom_pdf_docs
    type: pdf
    description: "PDF documents with custom processing configuration"
    config:
      # Custom configuration for PDFs
      llm:
        provider: "openai"
        config:
          model: "gpt-4o"
          temperature: 0.2
      chunker:
        chunk_size: 800
        chunk_overlap: 100
        length_function: "len"
    data:
      - "/path/to/document1.pdf"
      - "/path/to/document2.pdf"

  - name: custom_text_knowledge
    type: text
    description: "Text knowledge with custom processing"
    config:
      # Minimal configuration
      chunker:
        chunk_size: 500
        chunk_overlap: 50
    data:
      - |
        Custom Text Content:
        This is a custom text knowledge base with specific chunking configuration.
        The content will be processed according to the chunker_config settings.
        
        Key Features:
        - Custom chunk size: 500 characters
        - Custom overlap: 50 characters
        - Optimized for short text snippets

# Define agents in the team
agents:
  - name: "Custom Config Agent"
    instructions: >
      You are an agent that works with custom-configured knowledge bases.
      Use the knowledge_query tool to search through the custom-configured knowledge bases.
      Each knowledge base has specific chunking and processing settings optimized for its content type.
    model: gpt-4o
    temperature: 0.2
    tools:
      - knowledge_query
    knowledge:
      - custom_website_docs
      - custom_pdf_docs
      - custom_text_knowledge
